---
dependency:
  name: galaxy
platforms:
  - name: instance
    box: ubuntu/focal64
    interfaces:
      - network_name: private_network
        ip: 192.168.33.11
provisioner:
  name: ansible
verifier:
  name: ansible
